name: CI Pipeline

on:
  push:
    branches: [ "main" ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      # 현재 레포지토리 가져오기
      - name: Checkout repository
        uses: actions/checkout@v4



      # 도커 로그인
      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      # 도커 이미지 빌드하고 도커 허브에 push
      - name: Build and push the Docker image
        run: |
          TAG=$(date +%s)
          docker build -t $DOCKER_USERNAME/lpilogue-rec:$TAG -t $DOCKER_USERNAME/lpilogue-rec:latest .
          docker push $DOCKER_USERNAME/lpilogue-rec:$TAG
          docker push $DOCKER_USERNAME/lpilogue-rec:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

