name: CD Pipeline

on:
  workflow_run:
    # CI Pipeline이 실행된 후 실행
    workflows: [ "CI Pipeline" ]
    types:
      - completed


jobs:
  deploy:

    # 리눅스 서버의 Runner에서 실행
    runs-on: self-hosted
    steps:

      # 현재 레포지토리 가져오기
      - name: Checkout repository
        uses: actions/checkout@v4

      # Docker 로그인
      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      # Docker 이미지 Pull
      - name: Pull Docker image
        run: docker pull $DOCKER_USERNAME/lpilogue-rec:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

      # lpilogue-db가 실행중인 경우 중지
      - name: Stop lpilogue-db
        run: docker stop lpilogue-db || true && docker rm lpilogue-db || true

      # lpilogue-rec가 실행중인 경우 중지
      - name: Stop lpilogue-rec
        run: docker stop lpilogue-rec || true && docker rm lpilogue-rec || true

      # flask-app만 다시 실행
      - name: Run Docker compose
        run: docker compose rm -f flask-app && docker compose up -d flask-app
